inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - bin/**
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
